[package]
edition = "2021"
name = "pico-display"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = { workspace = true }
rand = { workspace = true }
num-traits = { version = "0.2.19", default-features = false }
trait-set = "0.3.0"
u8g2-fonts = { workspace = true }
