[tasks.build-server]
workspace = false
command = "cargo"
args = ["build", "--target=x86_64-unknown-linux-gnu"]

[tasks.clippy-all]
command = "cargo"
args = ["clippy", "--target=x86_64-unknown-linux-gnu", "--all"]
workspace = false
