name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  WIFI_NETWORK: "DUMMY_NETWORK"
  WIFI_PASSWORD: "DUMMY_PASSWORD"
  MEASUREMENTS_ENDPOINT: "http://dummy.dummy"

jobs:
  building:
    name: Building
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
            server-build-target: x86_64-unknown-linux-gnu
          - rust: stable
            os: ubuntu-latest
            server-build-target: x86_64-unknown-linux-gnu
          - rust: stable
            os: macOS-latest
            server-build-target: aarch64-apple-darwin
          - rust: stable
            os: windows-latest
            server-build-target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv8m.main-none-eabihf
      - run: cargo install flip-link
      - run: cargo build --all
      - run: cargo build --all --release
      - run: cargo build --all --release --features temperature
      - run: cargo build --manifest-path ./axum-server/Cargo.toml --target=${{ matrix.server-build-target }}
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          target: thumbv8m.main-none-eabihf
      - run: cargo clippy --all -- --deny=warnings
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          target: thumbv8m.main-none-eabihf
      - run: cargo fmt -- --check
