name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  WIFI_NETWORK: "DUMMY_NETWORK"
  WIFI_PASSWORD: "DUMMY_PASSWORD"
  MEASUREMENTS_ENDPOINT: "http://dummy.dummy"
  REST_USER: "DUMMY_REST_USER"
  REST_USER_PASSWORD: "DUMMY_REST_USER_PASSWORD"

jobs:
  building-rp2350:
    name: 'Building Board Code'
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv8m.main-none-eabihf
      - run: cargo install flip-link
      - run: cargo build --all
      - run: cargo build --all --release
      - run: cargo build --all --features temperature
      - run: cargo build --all --release --features temperature
  building-server:
    name: 'Building Server'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --all --manifest-path ./axum-server/Cargo.toml --target=x86_64-unknown-linux-gnu
      - run: cargo build --all --release --manifest-path ./axum-server/Cargo.toml --target=x86_64-unknown-linux-gnu
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          target: thumbv8m.main-none-eabihf
      - run: cargo clippy --all -- --deny=warnings
      - run: cargo clippy --all --features temperature -- --deny=warnings
      - run: cargo clippy --all --manifest-path ./axum-server/Cargo.toml --target=x86_64-unknown-linux-gnu -- --deny=warnings
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          target: thumbv8m.main-none-eabihf
      - run: cargo fmt -- --check
      - run: cargo fmt --manifest-path ./axum-server/Cargo.toml -- --check
  just:
    name: 'Runnig Just CI check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: 'Set up just'
        uses: extractions/setup-just@v3
        with:
          just-version: '1.46.0'

      - name: 'Create hub.env file'
        run: touch hub.env

      - name: 'Install frontend dependencies'
        run: just frontend install-deps

      - name: 'Lint the frontend'
        run: just frontend lint
