name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  WIFI_NETWORK: "DUMMY_NETWORK"
  WIFI_PASSWORD: "DUMMY_PASSWORD"
  MEASUREMENTS_ENDPOINT: "http://dummy.dummy"
  REST_USER: "DUMMY_REST_USER"
  REST_USER_PASSWORD: "DUMMY_REST_USER_PASSWORD"

jobs:
  building-rp2350:
    name: Building board code
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [nightly, stable]
        os: [macOS-latest, windows-latest]
        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv8m.main-none-eabihf
      - run: cargo install flip-link
      - run: cargo build --all
      - run: cargo build --all --release
      - run: cargo build --all --features temperature
      - run: cargo build --all --release --features temperature
  just-ci-check:
    name: Just CI check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          target: thumbv8m.main-none-eabihf
      - uses: actions/setup-node@v6
        with:
          node-version: '25'
      - uses: extractions/setup-just@v3
        with:
          just-version: '1.46.0'
      - run: touch hub.env
      - run: just ci-check
